cmake_minimum_required(VERSION 3.10)
project(deque)

add_executable(deque_construct_func 1.deque_construct_func.cpp)
add_executable(deqie_assignment 2.deqie_assignment.cpp)
add_executable(deque_capacity_operate 3.deque_capacity_operate.cpp)
add_executable(deque_insert_delete 4.deque_insert_delete.cpp)
add_executable(deque_date_access 5.deque_date_access.cpp)
add_executable(deque_sorting 6.deque_sorting.cpp)