cmake_minimum_required(VERSION 3.10)
project(list)

add_executable(1.list_construct_func 1.list_construct_func.cpp)
add_executable(2.list_assignment_swap 2.list_assignment_swap.cpp)
add_executable(3.list_capacity 3.list_capacity.cpp)
add_executable(4.list_insert_delete 4.list_insert_delete.cpp)
add_executable(5.list_data_access 5.list_data_access.cpp)
add_executable(6.list_reversal 6.list_reversal.cpp)
add_executable(7.list_sorting_demo 7.list_sorting_demo.cpp)